Repository SOPT-all/36-COLLABORATION-WEB-GOODOC, pull requests merged in 2025-05, with the labels that each got.

#2 Feat: svgr 초기 세팅
  package.json
  svg.d.ts
  tsconfig.app.json
  vite.config.ts
  yarn.lock
Labels: ⚙️Setting, 🐵지수

#4 Init: 프로젝트 폴더 구조 세팅
  index.html
  src/pages/chat/components/.gitkeep
  src/pages/chat/hooks/.gitkeep
  src/pages/chat/page/.gitkeep
  src/pages/main/components/.gitkeep
  src/pages/main/hooks/.gitkeep
  src/pages/main/page/.gitkeep
  src/pages/qna/hooks/.gitkeep
  src/pages/qna/qnaDetail/components/.gitkeep
  src/pages/qna/qnaDetail/page/.gitkeep
  src/pages/qna/qnaList/components/.gitkeep
  src/pages/qna/qnaList/page/.gitkeep
  src/shared/apis/api.ts
  src/shared/assets/images/.gitkeep
  src/shared/assets/svg/react.svg
  src/shared/components/.gitkeep
  src/shared/constants/constant.ts
  src/shared/hooks/.gitkeep
  src/shared/pages/.gitkeep
  src/shared/router/Router.tsx
  src/shared/styles/.gitkeep
  src/shared/types/.gitkeep
  src/shared/utils/.gitkeep
Labels: ⚙️Setting, 🐻지성

#8 Init: Tailwind 설치 및 Global Style 초기 세팅
  package.json
  postcss.config.cjs
  src/App.tsx
  src/main.tsx
  src/shared/styles/global.css
  tailwind.config.js
  yarn.lock
Labels: ⚙️Setting, 🐹희연

#7 Init: 절대 경로 설정
  package.json
  src/App.tsx
  tsconfig.app.json
  vite.config.ts
  yarn.lock
Labels: ⚙️Setting, 🐵지수

#10 Init: theme.css&global.css 파일 생성 및 스타일 작성
  package.json
  postcss.config.cjs
  postcss.config.js
  src/index.css
  src/main.tsx
  src/shared/styles/global.css
  src/shared/styles/theme.css
  tailwind.config.js
  yarn.lock
Labels: ⚙️Setting, 🐹희연

#11 Init: ESLint 및 Prettier 세팅
  .prettierignore
  .prettierrc
  eslint.config.js
  package.json
  postcss.config.js
  src/App.tsx
  src/main.tsx
  svg.d.ts
  tailwind.config.js
  vite.config.ts
  yarn.lock
Labels: ⚙️Setting, 🐰수연

#15 Init: CI/CD 자동 배포 환경 설정
  .github/workflows/deploy.yml
  build.sh
Labels: 🐵지수, 🌐Deploy

#13 Chore: Tanstack Query 설정
  package.json
  src/main.tsx
  yarn.lock
Labels: ⚙️Setting, 🐵지수

#17 Init: CI/CD 구축
  .github/CODEOWNERS
  .github/workflows/ci-cd.yml
  .github/workflows/deploy.yml
  vercel.json
  yarn.lock
Labels: ⚙️Setting, 🐵지수, 🌐Deploy

#18 Fix: 배포 브랜치 수정 및 리뷰어 변경
  .github/CODEOWNERS
  .github/workflows/deploy.yml
Labels: 🐞Fix, ⚙️Setting, 🐵지수

#20 Fix: 포크 동기화 오류 수정
  .github/workflows/deploy.yml
Labels: 🐞Fix, 🐵지수

#23 Feat: 채팅 뷰 헤더 컴포넌트 구현
  src/main.tsx
  src/shared/assets/svg/back-arrow.svg
  src/shared/assets/svg/menu.svg
  src/shared/components/Chat/ChatHeader.tsx
  src/shared/styles/global.css
Labels: ✨Feature, 🐵지수

#29 Chore: 폴더 변경
  src/pages/chat/components/.gitkeep
  src/pages/chat/components/ChatHeader.tsx
Labels: 🐵지수, 🔨Chore

#25 Feat: 채팅 뷰 입력창 컴포넌트 구현
  src/main.tsx
  src/pages/chat/components/ChatInput.tsx
  src/shared/assets/svg/send.svg
Labels: ✨Feature, 🐵지수

#35 Feat: QnAListItem 컴포넌트 구현
  src/main.tsx
  src/pages/qna/qnaList/components/QnAListItem.tsx
  src/shared/assets/svg/ellipsis.svg
Labels: ✨Feature, 🐻지성

#27 Feat: 채팅 뷰 버튼 컴포넌트 구현
  src/pages/chat/components/Button.tsx
  src/shared/styles/theme.css
  tsconfig.json
Labels: ✨Feature, 🐹희연

#33 Feat: 채팅 뷰 챗봇 메시지 컴포넌트 구현
  src/pages/chat/components/chatBot/ChatBubbleBot.tsx
  src/shared/assets/svg/chatProfile.svg
Labels: ✨Feature, 🐹희연

#41 Feat: 메인 뷰 필터 칩 컴포넌트 구현
  src/pages/main/components/FilterChip.tsx
  src/shared/assets/images/LogoCircle.png
  src/shared/assets/svg/IconCalendar.svg
  src/shared/assets/svg/IconDownwardArrowSmall.svg
  src/shared/assets/svg/IconMoon.svg
Labels: ✨Feature, 🐰수연

#37 Feat: 채팅 뷰 유저 메시지 컴포넌트 구현
  src/pages/chat/components/user/ChatUser.tsx
Labels: ✨Feature, 🐹희연

#39 Feat: 채팅 뷰 챗봇 시작 메시지 및 서비스 선택 박스 구현(1번째 챗봇 박스)
  src/pages/chat/components/chatBot/ChatBubbleBot.tsx
  src/pages/chat/components/chatBox/ChatWelcomeBox.tsx
Labels: ✨Feature, 🐹희연

#51 Feat: 채팅 뷰 배경화면 구현
  src/pages/chat/components/ChatBody.tsx
  src/pages/chat/components/ChatHeader.tsx
  src/pages/chat/components/ChatInput.tsx
  src/pages/chat/page/.gitkeep
  src/pages/chat/page/ChatPage.tsx
  src/shared/assets/svg/chatAlert.svg
  src/shared/styles/global.css
  src/shared/styles/theme.css
Labels: ✨Feature, 🐵지수

#47 feat: 위치 카테고리 컴포넌트 구현
  src/pages/main/components/LocationCategoryFilter.tsx
  src/shared/assets/svg/IconDownwardArrow.svg
  src/shared/assets/svg/IconMap.svg
Labels: ✨Feature, 🐰수연

#45 feat: 메인 뷰 헤더 컴포넌트 구현
  src/pages/main/components/MainHeader.tsx
  src/shared/assets/images/Logoheader.png
  src/shared/assets/svg/IconMenu.svg
  src/shared/assets/svg/IconSearch.svg
Labels: ✨Feature, 🐰수연

#50 feat: 메인 및 메뉴 뷰 버튼 컴포넌트 구현
  src/pages/main/components/MoreButton.tsx
  src/pages/menu/components/DownloadButton.tsx
  src/pages/menu/components/LoginButton.tsx
  src/pages/menu/hooks/.gitkeep
  src/pages/menu/page/.gitkeep
Labels: ✨Feature, 🐰수연

#40 Feat: 진료과 선택 컴포넌트 구현 등
  package.json
  src/main.tsx
  src/pages/qna/qnaList/components/.gitkeep
  src/pages/qna/qnaList/components/DeptFilter/DeptBox.tsx
  src/pages/qna/qnaList/components/DeptFilter/DeptFilter.tsx
  src/pages/qna/qnaList/components/QnA/QnAList.tsx
  src/pages/qna/qnaList/components/QnA/QnAListItem.tsx
  src/pages/qna/qnaList/components/hook/useDeptFilter.ts
  src/pages/qna/qnaList/page/.gitkeep
  src/pages/qna/qnaList/page/QnAHome.tsx
  src/shared/assets/svg/chevron-updown.svg
  src/shared/constants/constant.ts
  src/shared/styles/global.css
  tailwind.config.js
  yarn.lock
Labels: ✨Feature, 🐻지성

#54 Design: theme.css leading 값 수정
  src/shared/styles/theme.css
Labels: 🐹희연, 🎨Design

#55 Feat: QnAList 페이지 검색 컴포넌트, 내 질문 컴포넌트 구현
  src/pages/qna/qnaList/components/MyQuestion.tsx
  src/pages/qna/qnaList/components/QnASearch.tsx
  src/shared/assets/svg/IconForwardArrow.svg
  src/shared/assets/svg/IconSearch.svg
Labels: ✨Feature, 🐻지성

#65 feat: 채팅 뷰 복약 정보 메시지 박스 컴포넌트 구현 (4번째 챗봇 박스)
  src/pages/chat/components/chatBox/ChatMedicationBox.tsx
Labels: ✨Feature, 🐹희연

#62 Feat: 푸터 구현
  src/shared/assets/svg/ImageMark.svg
  src/shared/components/Footer.tsx
Labels: ✨Feature, 🐻지성

#61 Feat: 채팅 로직 구현
  src/App.tsx
  src/pages/chat/components/ChatBody.tsx
  src/pages/chat/components/ChatHeader.tsx
  src/pages/chat/components/chatBox/ChatBubbleBot.tsx
  src/pages/chat/components/chatBox/ChatQuestionBox.tsx
  src/pages/chat/components/chatBox/ChatWelcomeBox.tsx
  src/pages/chat/components/user/ChatUser.tsx
  src/shared/styles/animation.ts
  src/shared/styles/theme.css
  src/shared/utils/date.ts
Labels: ✨Feature, 🐵지수

#73 CHORE: 챗봇 메시지 컴포넌트 폴더 구조 변경에 따른 수정
  src/pages/chat/components/chatBox/ChatMedicationBox.tsx
Labels: 🐹희연, 🔨Chore

#72 Feat: 라우팅 설정
  src/App.tsx
  src/pages/qna/qnaDetail/page/.gitkeep
  src/pages/qna/qnaDetail/page/QnaDetail.tsx
  src/shared/router/Router.tsx
Labels: ⚙️Setting, 🐵지수

#76 Feat: QnA 리스트 페이지 디자인 완료
  package.json
  src/pages/qna/hooks/.gitkeep
  src/pages/qna/hooks/useDeptFilter.ts
  src/pages/qna/qnaList/components/DeptBox.tsx
  src/pages/qna/qnaList/components/DeptFilter.tsx
  src/pages/qna/qnaList/components/DeptFilter/DeptFilter.tsx
  src/pages/qna/qnaList/components/MyQuestion.tsx
  src/pages/qna/qnaList/components/QnAList.tsx
  src/pages/qna/qnaList/components/QnAListItem.tsx
  src/pages/qna/qnaList/components/QnASearch.tsx
  src/pages/qna/qnaList/page/QnAHome.tsx
  src/shared/components/Footer.tsx
  src/shared/components/QnAButton.tsx
  src/shared/router/Router.tsx
  yarn.lock
Labels: ✨Feature, 🐻지성

#79 Feat: 채팅 뷰 이미지 첨부 기능 구현 (5번째 챗봇 박스) #66
  src/pages/chat/components/Toast.tsx
  src/pages/chat/components/chatBox/ChatBubbleBot.tsx
  src/pages/chat/components/chatBox/ChatImageBox.tsx
  src/pages/chat/components/chatBox/ChatWelcomeBox.tsx
  src/pages/chat/components/user/ImagePreviewList.tsx
  src/shared/assets/svg/errorIcon.svg
  src/shared/styles/theme.css
Labels: ✨Feature, 🐹희연

#82 Feat: 메인 페이지 구현
  src/pages/main/components/GoodBotFAB.tsx
  src/pages/main/components/HospitalListItem.tsx
  src/pages/main/components/MoreButton.tsx
  src/pages/main/hooks/.gitkeep
  src/pages/main/hooks/UsePagination.tsx
  src/pages/main/page/.gitkeep
  src/pages/main/page/MainPage.tsx
  src/pages/menu/page/.gitkeep
  src/shared/assets/images/ImgGoodbotFAB.png
  src/shared/components/Footer.tsx
Labels: ✨Feature, 🐰수연

#85 Feat: QnA 공통 레이아웃 페이지(QnALayout) 생성 및 QnA 페이지 라우팅 설정
  src/pages/qna/page/QnALayout.tsx
  src/pages/qna/qnaList/page/QnAHome.tsx
  src/pages/qna/qnaMy/page/QnAMy.tsx
  src/shared/components/Footer.tsx
  src/shared/router/Router.tsx
Labels: ✨Feature, 🐻지성

#89 Feat: 질병 상세 설명 메시지 박스 컴포넌트 구현(7번째 챗봇 박스)
  src/pages/chat/components/chatBox/ChatAnswerBox.tsx
  src/pages/chat/components/chatBox/ChatMedicationBox.tsx
Labels: ✨Feature, 🐹희연

#63 Feat: 채팅 뷰 유저 상태 고려 옵션 박스 구현 (3번째 챗봇 박스)
  src/pages/chat/components/Button.tsx
  src/pages/chat/components/ChatBubbleBot.tsx
  src/pages/chat/components/SelectableButton.tsx
  src/pages/chat/components/chatBox/ChatConsiderationBox.tsx
  src/pages/chat/hooks/useSelectableOption.ts
  src/shared/styles/theme.css
Labels: ✨Feature, 🐹희연

#92 Feat: 질병 설명 요약&진료과 추천 메시지 컴포넌트 구현(8번째 챗봇 박스)
  src/pages/chat/components/Button.tsx
  src/pages/chat/components/chatBox/ChatSummaryBox.tsx
  src/shared/styles/theme.css
Labels: ✨Feature, 🐹희연

#94 Feat: API 설정 수정
  .gitignore
  package.json
  postcss.config.js
  src/pages/qna/qnaDetail/page/QnaDetail.tsx
  src/shared/apis/api.ts
  src/shared/apis/apiClient.ts
  src/shared/apis/qna/error.ts
  src/shared/apis/qna/qnaDetail.ts
  src/shared/apis/queryClient.ts
  src/shared/styles/theme.css
  tailwind.config.js
  yarn.lock
Labels: 🐵지수, 📬API

#100 Feat: 유저 상태 옵션 박스 컴포넌트 구현 (v2)
  src/pages/chat/components/SelectableButton.tsx
  src/pages/chat/components/chatBox/ChatConsiderationBox.tsx
  src/pages/chat/hooks/useSelectableOption.ts
  src/shared/styles/theme.css
Labels: ✨Feature, 🐹희연

#102 Feat: 채팅 뷰 모달 컴포넌트 구현
  src/pages/chat/components/Button.tsx
  src/pages/chat/components/ChatBody.tsx
  src/pages/chat/components/ChatModal.tsx
  src/pages/chat/hooks/useChatModal.ts
  src/pages/chat/page/ChatPage.tsx
  src/shared/styles/theme.css
Labels: ✨Feature, 🐹희연

#99 Feat: 단계별 채팅 구현
  .env
  src/pages/chat/components/Button.tsx
  src/pages/chat/components/ChatBody.tsx
  src/pages/chat/components/ChatHeader.tsx
  src/pages/chat/components/ChatInput.tsx
  src/pages/chat/components/NextQuestionButton.tsx
  src/pages/chat/components/SelectableButton.tsx
  src/pages/chat/components/chatBox/ChatBubbleBot.tsx
  src/pages/chat/components/chatBox/ChatConsiderationBox.tsx
  src/pages/chat/components/chatBox/ChatImageBox.tsx
  src/pages/chat/components/chatBox/ChatQuestionBox.tsx
  src/pages/chat/components/chatBox/ChatWelcomeBox.tsx
  src/pages/chat/components/modal/ChatModal.tsx
  src/pages/chat/components/modal/ExitModal.tsx
  src/pages/chat/hooks/.gitkeep
  src/pages/chat/hooks/useAutoScrollToBottom.ts
  src/pages/chat/hooks/useUserStartTime.ts
  src/pages/chat/page/ChatPage.tsx
  src/shared/assets/svg/Group.svg
  src/shared/constants/chatMessages.ts
  src/shared/utils/chat.ts
Labels: ✨Feature, 🐵지수

#110 Fix: 메인페이지 자체 QA 반영
  src/pages/main/page/MainPage.tsx
Labels: 🐞Fix, 🐰수연

#113 Feat: 채팅 기능 보완
  src/pages/chat/components/ChatBody.tsx
  src/pages/chat/components/chatBox/ChatSummaryBox.tsx
  src/pages/chat/hooks/useUserStartTime.ts
Labels: 🐞Fix, ✨Feature, 🐵지수

#114 Fix: 문자 포맷팅 함수 수정
  src/shared/utils/formatText.tsx
Labels: 🐞Fix, 🐵지수

#117 Fix: 포맷팅 함수 수정
  src/shared/utils/formatText.tsx
Labels: 🐞Fix, 🐵지수

#118 Feat: 채팅 오류 수정
  src/pages/chat/components/ChatBody.tsx
  src/pages/chat/components/ChatInput.tsx
  src/pages/chat/components/chatBox/ChatImageBox.tsx
Labels: 🐞Fix, 🐵지수

#119 Feat: 사진 첨부 로직 수정
  src/pages/chat/components/chatBox/ChatImageBox.tsx
Labels: 🐞Fix, 🐵지수

#120 Refactor: 채팅 코드 리팩토링
  src/pages/chat/components/ChatBody.tsx
  src/pages/chat/components/chatFlow/ChatResultSection.tsx
  src/pages/chat/components/chatFlow/QuestionFlowSection.tsx
  src/pages/chat/components/user/UserMessageList.tsx
  src/pages/chat/hooks/useChatMessageManager.ts
  src/shared/pages/.gitkeep
  src/shared/types/.gitkeep
  src/shared/types/chat.ts
Labels: 🐵지수, 🛠️Refactor
